### ISSUE TITLE
Error while following example_FFM_criteo.py

### ISSUE THREAD

**Issue by atkm** [aksnzhy/xlearn#164]
The following code from ./demo/classification/scikit_learn_demo/example_FFM_criteo.py produces the error below. I am using Python 3.6.6 in a virtualenv. numpy==1.15.2, xlearn==0.32a1.

Code:
```
import xlearn as xl
import numpy as np

ffm = xl.FFMModel(task='binary', lr=0.2, epoch=10, reg_lambda=0.002, metric='acc')
ffm.fit('./data/small_train.txt')
```

Output (truncated to 60 lines. The output is 84977 lines untruncated):
```
[32m[1m----------------------------------------------------------------------------------------------
           _
          | |
     __  _| |     ___  __ _ _ __ _ __
     \ \/ / |    / _ \/ _` | '__| '_ \ 
      >  <| |___|  __/ (_| | |  | | | |
     /_/\_\_____/\___|\__,_|_|  |_| |_|

        xLearn   -- 0.32 Version --
----------------------------------------------------------------------------------------------

[39m[0m[35m[1m[ WARNING    ] Validation file not found, xLearn has already disable early-stopping.[0m
[35m[1m[ WARNING    ] Validation file not found, xLearn has already disable (-x acc) option.[0m
[32m[1m[ ACTION     ] Read Problem ...[0m
[32m[------------] [0mFirst check if the text file has been already converted to binary format.
[32m[------------] [0mBinary file (./data/small_train.txt.bin) found. Skip converting text to binary.
[32m[------------] [0mNumber of Feature: 9991
[32m[------------] [0mNumber of Field: 18
[32m[------------] [0mTime cost for reading problem: 0.00 (sec)
[32m[1m[ ACTION     ] Initialize model ...[0m
[32m[------------] [0mModel size: 2.78 MB
[32m[------------] [0mTime cost for model initial: 0.00 (sec)
[32m[1m[ ACTION     ] Start to train ...[0m
[32m[------------][0m Epoch      Train log_loss     Time cost (sec)
[32m[ [0m  10%[32m      ][0m     1            0.570255                0.00
[32m[ [0m  20%[32m      ][0m     2            0.543137                0.00
[32m[ [0m  30%[32m      ][0m     3            0.522801                0.00
[32m[ [0m  40%[32m      ][0m     4            0.514261                0.00
[32m[ [0m  50%[32m      ][0m     5            0.499862                0.00
[32m[ [0m  60%[32m      ][0m     6            0.488135                0.00
[32m[ [0m  70%[32m      ][0m     7            0.479988                0.00
[32m[ [0m  80%[32m      ][0m     8            0.475955                0.00
[32m[ [0m  90%[32m      ][0m     9            0.462206                0.00
[32m[ [0m 100%[32m      ][0m    10            0.445083                0.00
[32m[1m[ ACTION     ] Start to save model ...[0m
[32m[------------] [0mModel file: /tmp/tmphm0eripl
[32m[------------] [0mTime cost for saving model: 0.00 (sec)
[32m[1m[ ACTION     ] Start to save txt model ...[0m
[32m[------------] [0mTXT Model file: /tmp/tmphbq3lk48
[32m[------------] [0mTime cost for saving txt model: 0.36 (sec)
[32m[1m[ ACTION     ] Finish training[0m
[32m[1m[ ACTION     ] Clear the xLearn environment ...[0m
[32m[1m[------------] Total time cost: 0.38 (sec)[0m
Traceback (most recent call last):
  File "ffm_example_criteo.py", line 5, in <module>
    ffm.fit('./data/small_train.txt')
  File "/home/atkm/code/avazu-ctr/venv/lib/python3.6/site-packages/xlearn/_sklearn.py", line 275, in fit
    self._parse_weight(self._temp_weight_file.name)
  File "/home/atkm/code/avazu-ctr/venv/lib/python3.6/site-packages/xlearn/_sklearn.py", line 344, in _parse_weight
    weight_vec = np.genfromtxt(file_name, skip_footer=num_features)
  File "/home/atkm/code/avazu-ctr/venv/lib/python3.6/site-packages/numpy/lib/npyio.py", line 2031, in genfromtxt
    raise ValueError(errmsg)
ValueError: Some errors were detected !
    Line #9993 (got 5 columns instead of 2)
    Line #9994 (got 5 columns instead of 2)
    Line #9995 (got 5 columns instead of 2)
    Line #9996 (got 5 columns instead of 2)
    Line #9997 (got 5 columns instead of 2)
    Line #9998 (got 5 columns instead of 2)
    Line #9999 (got 5 columns instead of 2)
   ... (many more lines)
```

**Comment by atkm** [comment]
Ok. Thanks.
