### ISSUE TITLE
XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path

### ISSUE THREAD

**Issue by johnwanggithub** [aksnzhy/xlearn#198]
hi I met following problems when I install the xlearn on centos,  could pls have a look at on this? thanks in advance. @aksnzhy 

-- Configuring done
-- Generating done
-- Build files have been written to: /root/xlearn/xlearn-master/build
[  1%] Building CXX object gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
/tmp/ccSQqXA3.s: Assembler messages:
/tmp/ccSQqXA3.s:7038: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm2,%ymm1'
/tmp/ccSQqXA3.s:7039: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/ccSQqXA3.s:7040: Error: suffix or operands invalid for `vpsubd'
/tmp/ccSQqXA3.s:7045: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:7047: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:7049: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:7051: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:7052: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:7053: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm1'
/tmp/ccSQqXA3.s:7054: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:7055: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:7196: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm2,%ymm1'
/tmp/ccSQqXA3.s:7197: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/ccSQqXA3.s:7198: Error: suffix or operands invalid for `vpsubd'
/tmp/ccSQqXA3.s:7203: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:7205: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:7207: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:7209: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:7210: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:7211: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm1'
/tmp/ccSQqXA3.s:7212: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:7213: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:8024: Error: no such instruction: `vpbroadcastq %xmm5,%ymm0'
/tmp/ccSQqXA3.s:8025: Error: suffix or operands invalid for `vpaddq'
/tmp/ccSQqXA3.s:8028: Error: suffix or operands invalid for `vpaddq'
/tmp/ccSQqXA3.s:8031: Error: no such instruction: `vperm2i128 $32,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:8032: Error: no such instruction: `vperm2i128 $49,%ymm1,%ymm0,%ymm1'
/tmp/ccSQqXA3.s:8033: Error: suffix or operands invalid for `vpaddq'
/tmp/ccSQqXA3.s:8034: Error: suffix or operands invalid for `vpshufd'
/tmp/ccSQqXA3.s:8035: Error: suffix or operands invalid for `vpshufd'
/tmp/ccSQqXA3.s:8036: Error: suffix or operands invalid for `vpunpcklqdq'
/tmp/ccSQqXA3.s:12541: Error: no such instruction: `vpbroadcastq %xmm6,%ymm0'
/tmp/ccSQqXA3.s:12542: Error: suffix or operands invalid for `vpaddq'
/tmp/ccSQqXA3.s:12544: Error: suffix or operands invalid for `vpaddq'
/tmp/ccSQqXA3.s:12547: Error: no such instruction: `vperm2i128 $32,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:12548: Error: no such instruction: `vperm2i128 $49,%ymm1,%ymm0,%ymm1'
/tmp/ccSQqXA3.s:12549: Error: suffix or operands invalid for `vpaddq'
/tmp/ccSQqXA3.s:12550: Error: suffix or operands invalid for `vpshufd'
/tmp/ccSQqXA3.s:12551: Error: suffix or operands invalid for `vpshufd'
/tmp/ccSQqXA3.s:12552: Error: suffix or operands invalid for `vpunpcklqdq'
/tmp/ccSQqXA3.s:39265: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm2,%ymm1'
/tmp/ccSQqXA3.s:39266: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/ccSQqXA3.s:39267: Error: suffix or operands invalid for `vpsubd'
/tmp/ccSQqXA3.s:39272: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:39274: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:39276: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:39278: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:39279: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:39280: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm1'
/tmp/ccSQqXA3.s:39281: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:39282: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:39447: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm2,%ymm1'
/tmp/ccSQqXA3.s:39448: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/ccSQqXA3.s:39449: Error: suffix or operands invalid for `vpsubd'
/tmp/ccSQqXA3.s:39454: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:39456: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:39458: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:39460: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:39461: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:39462: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm1'
/tmp/ccSQqXA3.s:39463: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:39464: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:59022: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm2,%ymm1'
/tmp/ccSQqXA3.s:59023: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/ccSQqXA3.s:59024: Error: suffix or operands invalid for `vpsubd'
/tmp/ccSQqXA3.s:59029: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:59031: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:59033: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:59035: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:59036: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:59037: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm1'
/tmp/ccSQqXA3.s:59038: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:59039: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:59625: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/ccSQqXA3.s:59626: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/ccSQqXA3.s:59627: Error: suffix or operands invalid for `vpsubd'
/tmp/ccSQqXA3.s:59632: Error: no such instruction: `vperm2i128 $33,%ymm0,%ymm4,%ymm1'
/tmp/ccSQqXA3.s:59634: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:59636: Error: no such instruction: `vperm2i128 $33,%ymm0,%ymm4,%ymm1'
/tmp/ccSQqXA3.s:59638: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:59639: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:59640: Error: no such instruction: `vperm2i128 $33,%ymm0,%ymm4,%ymm0'
/tmp/ccSQqXA3.s:59641: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:59642: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:60903: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/ccSQqXA3.s:60904: Error: suffix or operands invalid for `vpcmpeqd'
/tmp/ccSQqXA3.s:60905: Error: suffix or operands invalid for `vpsubd'
/tmp/ccSQqXA3.s:60910: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm4,%ymm0'
/tmp/ccSQqXA3.s:60912: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:60914: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm2'
/tmp/ccSQqXA3.s:60916: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:60917: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:60918: Error: no such instruction: `vperm2i128 $33,%ymm1,%ymm0,%ymm1'
/tmp/ccSQqXA3.s:60919: Error: suffix or operands invalid for `vpalignr'
/tmp/ccSQqXA3.s:60920: Error: suffix or operands invalid for `vpaddd'
/tmp/ccSQqXA3.s:61279: Error: no such instruction: `vpbroadcastq %xmm5,%ymm2'
/tmp/ccSQqXA3.s:61280: Error: suffix or operands invalid for `vpaddq'
/tmp/ccSQqXA3.s:61282: Error: suffix or operands invalid for `vpaddq'
/tmp/ccSQqXA3.s:61285: Error: no such instruction: `vperm2i128 $32,%ymm0,%ymm2,%ymm1'
/tmp/ccSQqXA3.s:61286: Error: no such instruction: `vperm2i128 $49,%ymm0,%ymm2,%ymm0'
/tmp/ccSQqXA3.s:61287: Error: suffix or operands invalid for `vpaddq'
/tmp/ccSQqXA3.s:61288: Error: suffix or operands invalid for `vpshufd'
/tmp/ccSQqXA3.s:61289: Error: suffix or operands invalid for `vpshufd'
/tmp/ccSQqXA3.s:61290: Error: suffix or operands invalid for `vpunpcklqdq'
make[2]: *** [gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [gtest/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2
/usr/bin/python2
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
/opt/tuniu/anaconda3/bin/python3
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    LIB_PATH = [os.path.relpath(libfile, CURRENT_DIR) for libfile in libpath['find_lib_path']()]
  File "xlearn/libpath.py", line 59, in find_lib_path
    'Cannot find xlearn Library in the candidate path'
XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path

**Comment by yuanbaopeng** [comment]
gcc 版本太高，试试gcc4.8.5

**Comment by gongtian1234** [comment]
我也出现了这个问题，楼主是怎么解决的

**Comment by Sandy4321** [comment]
same get on windows 
\xlearn\libpath.py", line 58, in find_lib_path
    raise XLearnLibraryNotFound(

full message is 
import xlearn as xl
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn_init_.py", line 18, in
from .xlearn import *
File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn\xlearn.py", line 19, in
from .base import _LIB, XLearnHandle
File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn\base.py", line 34, in
_LIB = _load_lib()
File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn\base.py", line 27, in _load_lib
lib_path = find_lib_path()
File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn\libpath.py", line 59, in find_lib_path
'Cannot find xlearn Library in the candidate path'
xlearn.libpath.XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path
