### ISSUE TITLE
install erro

### ISSUE THREAD

**Issue by Jie-Yuan** [aksnzhy/xlearn#211]
pip install xlearn -U
Collecting xlearn
  Using cached https://files.pythonhosted.org/packages/ab/1b/9ad0093cac05d6f95d3d768bc855804b18723c72120ce45cd930bd303587/xlearn-0.40a1.tar.gz
Building wheels for collected packages: xlearn
  Running setup.py bdist_wheel for xlearn ... error
  Complete output from command /home/yuanjie/desktop/software/intelpython3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0z35bwz6/xlearn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-7znp7vj9 --python-tag cp36:
  /home/yuanjie/.local/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.40.a1' to '0.40a1'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 37, in silent_call
      subprocess.check_output(cmd, stderr=shut_up)
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/subprocess.py", line 336, in check_output
      **kwargs).stdout
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/subprocess.py", line 403, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/subprocess.py", line 709, in __init__
      restore_signals, start_new_session)
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/subprocess.py", line 1344, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 126, in <module>
      url='https://github.com/aksnzhy/xlearn')
    File "/home/yuanjie/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 104, in run
      compile_cpp()
    File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 75, in compile_cpp
      silent_call(cmake_cmd, raise_error=True, error_msg='Please install CMake first')
    File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 41, in silent_call
      raise Exception(error_msg);
  Exception: Please install CMake first
  
  ----------------------------------------
  Failed building wheel for xlearn
  Running setup.py clean for xlearn
Failed to build xlearn
Installing collected packages: xlearn
  Running setup.py install for xlearn ... error
    Complete output from command /home/yuanjie/desktop/software/intelpython3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0z35bwz6/xlearn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2c_yqo66/install-record.txt --single-version-externally-managed --compile:
    /home/yuanjie/.local/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.40.a1' to '0.40a1'
      normalized_version,
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 37, in silent_call
        subprocess.check_output(cmd, stderr=shut_up)
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 126, in <module>
        url='https://github.com/aksnzhy/xlearn')
      File "/home/yuanjie/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 93, in run
        install.run(self)
      File "/home/yuanjie/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/yuanjie/desktop/software/intelpython3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 104, in run
        compile_cpp()
      File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 75, in compile_cpp
        silent_call(cmake_cmd, raise_error=True, error_msg='Please install CMake first')
      File "/tmp/pip-install-0z35bwz6/xlearn/setup.py", line 41, in silent_call
        raise Exception(error_msg);
    Exception: Please install CMake first
    
    ----------------------------------------
Command "/home/yuanjie/desktop/software/intelpython3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0z35bwz6/xlearn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2c_yqo66/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-0z35bwz6/xlearn/

**Comment by daisy-belle** [comment]
already installed cmake, but installing through pip is still the same problem

**Comment by aksnzhy** [comment]
@daisy-belle Hi, could you please provide the error information? Thanks!
