### ISSUE TITLE
xlearn was installed on windows anaconda successfully  but is not working 

### ISSUE THREAD

**Issue by Sandy4321** [aksnzhy/xlearn#364]
xlearn was installed on windows anaconda successfully  but is not working 
error is
>>> import xlearn as xl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn\__init__.py", line 18, in <module>
    from .xlearn import *
  File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn\xlearn.py", line 19, in <module>
    from .base import _LIB, XLearnHandle
  File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn\base.py", line 34, in <module>
    _LIB = _load_lib()
  File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn\base.py", line 27, in _load_lib
    lib_path = find_lib_path()
  File "C:\Users\sndr\anaconda3_Apr_2020\lib\site-packages\xlearn\libpath.py", line 59, in find_lib_path
    'Cannot find xlearn Library in the candidate path'
xlearn.libpath.XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path

**Comment by Liwan-Chen** [comment]
Did you solve the problem? I have the same issue.
