### ISSUE TITLE
why the model.out content is messy code

### ISSUE THREAD

**Issue by HuangZhanPeng** [aksnzhy/xlearn#63]
�?�?�?�?�?�?�<���?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?��޾4�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?}���:8@�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�ω=��?�?�?�I�����?�?�?�?�?�?�?�?�?�?�?�?�?�?A��W'�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?��>C�?�?�?�?�?�?�?�?�?�?�?�?<-l��9�?�?�?�?�?�?�?�?�?�?�?�?�?�ܽ,�?�?�?m2о�}Q@�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?>>?�?�9d=®�?��(>�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�S�'�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?���>!6�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?++?�@�?Ű�{Y�?�?�?�?ۀ��?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�]X�Uف?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�mt>#E�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�y��&�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�?�??M&=>n

**Comment by HuangZhanPeng** [comment]
I have another problem, when I run the code:

from __future__ import absolute_import
import xlearn as xl

ffm_model = xl.create_ffm()

ffm_model.setTrain('./data/train_ffm.txt')
ffm_model.setValidate('./data/valid_ffm.txt')

param = {'task': 'binary', 'lr': 0.2, 'lambda': 0.002, 'nthread': 8, 'epoch': 10}

ffm_model.fit(param, './ffm_model.out')

ffm_model.setTest('./data/test_ffm.txt')
ffm_model.predict('./ffm_model.out', './ffm_output.txt')

it has raise the error:
Traceback (most recent call last):
  File "xlearn.py", line 3, in <module>
    import xlearn as xl
  File "/home/huangzhanpeng/Download/criteo/kaggle_criteo_ctr_challenge-/xlearn.py", line 5, in <module>
    ffm_model = xl.create_ffm()
AttributeError: 'module' object has no attribute 'create_ffm'

but the code can run in jupyter notebook

**Comment by aksnzhy** [comment]
It's a strange error I have never met before.  I will check this soon.

**Comment by HuangZhanPeng** [comment]
there is another strange thing that if not delete xlearn.pyc, while create another python script, it still raise the same error

**Comment by johnwanggithub** [comment]
@HuangZhanPeng 请问后来 'module' object has no attribute 'create_ffm' 这个问题怎么解决的，我也遇到了同样的问题，谢谢。

**Comment by aksnzhy** [comment]
@johnwanggithub 你能把 code 放上来吗，我帮你 check 一下。

**Comment by HuangZhanPeng** [comment]
@johnwanggithub 我删除了.pyc文件后就可以了
