### ISSUE TITLE
when I hstack 2 csr_matrix ,xlearn failed to convert feature matrix X and label y to xlearn data format

### ISSUE THREAD

**Issue by hutaohutc** [aksnzhy/xlearn#82]
here is my code :
```
X_train_ext = hstack([X_trans[:100000, :],hotelid_tran[:100000, :] ])
X_test_ext = hstack([X_trans[100000:, :],hotelid_tran[100000:, :] ])
fm_model = xl.FMModel(task='binary', init=0.66, 
                      epoch=10, k=4, lr=0.01,
                      reg_lambda=0.1, opt='adagrad', 
                      metric='auc')
fm_model.fit(X_train_ext,train_y,eval_set=[X_test_ext, test_y])
```

```
Traceback (most recent call last):
  File "/home/qj/anaconda3/lib/python3.6/site-packages/xlearn-0.3.0-py3.6.egg/xlearn/_sklearn.py", line 286, in _convert_data
    write_data_to_xlearn_format(X, y, filepath, fields=fields)
  File "/home/qj/anaconda3/lib/python3.6/site-packages/xlearn-0.3.0-py3.6.egg/xlearn/_sklearn.py", line 50, in write_data_to_xlearn_format
    span = slice(X.indptr[i], X.indptr[i + 1])
  File "/home/qj/anaconda3/lib/python3.6/site-packages/scipy/sparse/base.py", line 647, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: indptr not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qj/anaconda3/lib/python3.6/site-packages/xlearn-0.3.0-py3.6.egg/xlearn/_sklearn.py", line 223, in fit
    self._convert_data(X_val, y_val, temp_val_file.name, fields=self.fields)
  File "/home/qj/anaconda3/lib/python3.6/site-packages/xlearn-0.3.0-py3.6.egg/xlearn/_sklearn.py", line 288, in _convert_data
    raise Exception('failed to convert feature matrix X and label y to xlearn data format')
Exception: failed to convert feature matrix X and label y to xlearn data format
```

It can work when I use only one csr_matrix without using `hstack` ,thank you for you answer~

**Comment by aksnzhy** [comment]
@randxie  Please review this issue.

**Comment by randxie** [comment]
@hutaohutc Thanks for testing the sklearn interface. The reason is when you do hstack of two csr matrices, the output becomes scipy.sparse.coo.coo_matrix. One quick fix is to enforce the hstack output to csr matrix as following.

X_train_ext = hstack([X_trans[:100000, :],hotelid_tran[:100000, :] ]).tocsr()
X_test_ext = hstack([X_trans[100000:, :],hotelid_tran[100000:, :] ]).tocsr()

I also find out that I forget to add check_X_y to eval_set. It is the reason why the conversion fails in [X_val, y_val].

**Comment by aksnzhy** [comment]
Fixed and close issue.
