### ISSUE TITLE
pip install test error.

### ISSUE THREAD

**Issue by classtag** [aksnzhy/xlearn#87]
Hi aksnzhy:

I used pip install xlearn in a conda enviment, but occur some issue as bellow log, please check

```bash

(stats27) > $ pip install xlearn                                                                                                                     ⬡ 7.9.0
Collecting xlearn
  Downloading http://mirrors.aliyun.com/pypi/packages/0c/2d/a5a873d5de6aa602f5ef8fe54516adbfe2edba0a284469e231621f3164f3/xlearn-0.30a1.tar.gz (2.1MB)
    100% |████████████████████████████████| 2.1MB 6.9MB/s
Building wheels for collected packages: xlearn
  Running setup.py bdist_wheel for xlearn ... done
  Stored in directory: /Users/duoan/Library/Caches/pip/wheels/00/d8/2e/89cb5f81d13f3c2543ecdc7a43129bdeabeb7b81300b60c61d
Successfully built xlearn
Installing collected packages: xlearn
Successfully installed xlearn-0.30a1

duoan@9801a7aef203 ~/Documents/nbs/tianchi/ijcai/src                                                                                               [20:53:26]
(stats27) > $ python                                                                                                                                 ⬡ 7.9.0
Python 2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:18:54)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xlearn as xl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/duoan/.anaconda/envs/stats27/lib/python2.7/site-packages/xlearn/__init__.py", line 4, in <module>
    from .xlearn import *
  File "/Users/duoan/.anaconda/envs/stats27/lib/python2.7/site-packages/xlearn/xlearn.py", line 5, in <module>
    from .base import _LIB, XLearnHandle
  File "/Users/duoan/.anaconda/envs/stats27/lib/python2.7/site-packages/xlearn/base.py", line 20, in <module>
    _LIB = _load_lib()
  File "/Users/duoan/.anaconda/envs/stats27/lib/python2.7/site-packages/xlearn/base.py", line 13, in _load_lib
    lib_path = find_lib_path()
  File "/Users/duoan/.anaconda/envs/stats27/lib/python2.7/site-packages/xlearn/libpath.py", line 45, in find_lib_path
    'Cannot find xlearn Library in the candidate path'
xlearn.libpath.XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path
```

**Comment by classtag** [comment]
And I try to build from source , it works OK.

**Comment by aksnzhy** [comment]
@purkyston Many people meet this problem. Can you figure out why it happens?

**Comment by purkyston** [comment]
It looks like there is no `libxlearn_api.dylib` in this directory `/Users/duoan/.anaconda/envs/stats27/lib/python2.7/site-packages/xlearn/`, which is built from the source code.
There is no problem on the Linux platform with anaconda.
I will check on the OS X.

**Comment by vnnw** [comment]
https://github.com/aksnzhy/xlearn/blob/4a7a7341dd31ee34939b4db54c76d065ae6fd34a/python-package/xlearn/libpath.py#L22

```
    # dll_path = [curr_path, os.path.join(curr_path, '../../lib/'),
   dll_path = [curr_path, os.path.join(curr_path, '../../build/lib/'),
```
I think this line is the problem.

**Comment by hhlisme** [comment]
@aksnzhy @vnnw How do I solve this problem when it happens under Windows?

**Comment by vnnw** [comment]
@hhlisme sorry, i don't have access to Windows.  
But i think the bug is the wrong path, so you may try to correct it with the code i've provided above and see if it works.

**Comment by hhlisme** [comment]
@aksnzhy @vnnw Yes, I think you're right. The 'lib_path' in libpath.py is an empty list.

**Comment by wuhaotju** [comment]
大佬，真巧，我也IJCAI，正在安装xlearn 可是出了点问题，能加个好友咨询下吗？
